# -*- coding: utf-8 -*-

from typing import Optional


class CurrencyCode:
    @staticmethod
    def get_code(symbol: str) -> Optional[str]:
        """Converts provided currency symbol into currency code.

        Parameters
        ----------
        symbol : str
            ISO 4217 - Currency Codes

        Returns
        -------
        Optional[str]
            Currency code, None if not exists.
        """

        return SYMBOLS_CURRENCY_MAP.get(symbol, symbol)


SYMBOLS_CURRENCY_MAP = {
    '$': 'USD',
    '€': 'EUR',
    '¥': 'JPY',
    'CN¥': 'CNY',
    '₩': 'KRW',
    'CA$': 'CAD',
    'A$': 'AUD',
    "د.إ": "AED",
    "؋": "AFN",
    "L": "ALL",
    "֏": "AMD",
    "ƒ": "ANG",
    "Kz": "AOA",
    "ƒ": "AWG",
    "₼": "AZN",
    "KM": "BAM",
    "৳": "BDT",
    "лв": "BGN",
    ".د.ب": "BHD",
    "FBu": "BIF",
    "$b": "BOB",
    "R$": "BRL",
    "฿": "BTC",
    "Nu.": "BTN",
    "P": "BWP",
    "Br": "BYN",
    "BZ$": "BZD",
    "FC": "CDF",
    "CHF": "CHF",
    "₡": "CRC",
    "₱": "CUP",
    "Kč": "CZK",
    "Fdj": "DJF",
    "kr": "DKK",
    "RD$": "DOP",
    "دج": "DZD",
    "Nfk": "ERN",
    "Br": "ETB",
    "Ξ": "ETH",
    "€": "EUR",
    "£": "GBP",
    "₾": "GEL",
    "₵": "GHC",
    "GH₵": "GHS",
    "D": "GMD",
    "FG": "GNF",
    "Q": "GTQ",
    "L": "HNL",
    "kn": "HRK",
    "G": "HTG",
    "Ft": "HUF",
    "Rp": "IDR",
    "₪": "ILS",
    "₹": "INR",
    "ع.د": "IQD",
    "﷼": "IRR",
    "J$": "JMD",
    "JD": "JOD",
    "¥": "JPY",
    "KSh": "KES",
    "៛": "KHR",
    "CF": "KMF",
    "₩": "KRW",
    "KD": "KWD",
    "₸": "KZT",
    "₭": "LAK",
    "₨": "LKR",
    "M": "LSL",
    "Ł": "LTC",
    "Lt": "LTL",
    "Ls": "LVL",
    "LD": "LYD",
    "MAD": "MAD",
    "lei": "MDL",
    "Ar": "MGA",
    "ден": "MKD",
    "K": "MMK",
    "₮": "MNT",
    "MOP$": "MOP",
    "UM": "MRO",
    "₨": "MUR",
    "Rf": "MVR",
    "MK": "MWK",
    "RM": "MYR",
    "MT": "MZN",
    "₦": "NGN",
    "C$": "NIO",
    "₨": "NPR",
    "﷼": "OMR",
    "B/.": "PAB",
    "S/.": "PEN",
    "K": "PGK",
    "₱": "PHP",
    "₨": "PKR",
    "zł": "PLN",
    "Gs": "PYG",
    "﷼": "QAR",
    "￥": "RMB",
    "lei": "RON",
    "Дин.": "RSD",
    "₽": "RUB",
    "R₣": "RWF",
    "﷼": "SAR",
    "₨": "SCR",
    "ج.س.": "SDG",
    "Le": "SLL",
    "S": "SOS",
    "Db": "STD",
    "E": "SZL",
    "฿": "THB",
    "SM": "TJS",
    "T": "TMT",
    "د.ت": "TND",
    "T$": "TOP",
    "₺": "TRY",
    "TT$": "TTD",
    "NT$": "TWD",
    "TSh": "TZS",
    "₴": "UAH",
    "USh": "UGX",
    "$U": "UYU",
    "Bs": "VEF",
    "₫": "VND",
    "VT": "VUV",
    "WS$": "WST",
    "FCFA": "XAF",
    "Ƀ": "XBT",
    "CFA": "XOF",
    "₣": "XPF",
    "﷼": "YER",
    "R": "ZAR",
    "Z$": "ZWD",
}
